#!/bin/sh

# Load up GHCi with an appropriate environment
#
DISTDIR=$(stack path --dist-dir)
stack exec ghci -- \
  $DISTDIR/build/cbits/twine_f32.o \
  $DISTDIR/build/cbits/twine_f64.o \
  -j +RTS -N -A64M -n2m -RTS \
  -fno-ghci-sandbox \
  $@

